console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯ '
  foreground = '#0DFF82'
  background = 'transparent'

[transient_prompt]
  template = '➜ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}#F44B5A{{end}}', '{{if eq .Code 0}}#0DFF82{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = false

  [[blocks.segments]]
    template = ' '
    foreground = '#D9D9D9'
    background = 'transparent'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = '#00B5E2'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String | replace "~" "" }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String |replace "~" "*" }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = '#0DFF82'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      branch_identical_icon = ""
      commit_icon = '@'
      fetch_status = true
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = '#D9D9D9'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 100

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '➜'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#0DFF82{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
